package com.anureet.nestedrecyclerviewexample.ui

import android.os.Bundle
import android.support.v4.media.session.MediaSessionCompat.Token.fromBundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.core.content.ContextCompat
import androidx.fragment.app.viewModels
import androidx.lifecycle.Observer
import androidx.activity.viewModels
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.ViewModelProviders
import com.anureet.nestedrecyclerviewexample.R
import com.anureet.nestedrecyclerviewexample.data.Categories
import com.anureet.nestedrecyclerviewexample.data.Favourites
import kotlinx.android.synthetic.main.fragment_favourite_detail.*

class FavouriteDetailFragment : Fragment() {

    private lateinit var viewModel: FavouriteDetailViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        viewModel = ViewModelProvider(this).get(FavouriteDetailViewModel::class.java)
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_favourite_detail, container, false)
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)

        val categories = mutableListOf<String>()
        Categories.values().forEach { categories.add(it.name) }
        val arrayAdapter =
            ArrayAdapter(requireActivity(), android.R.layout.simple_spinner_item, categories)
        category_spinner.adapter = arrayAdapter

        save_button.setOnClickListener {
            saveTask()
        }
    }


    private fun saveTask(){
        val name = name.text.toString()
        val category = category_spinner.selectedItemPosition

        // Saving item inside database
        // id is autogenerated, insert methods treat 0 as not-set while inserting the item.
        val item = Favourites(0, name, category)
        viewModel.saveTask(item)

        requireActivity().onBackPressed()
    }

}